# Build the service
FROM node:22

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# Container to run the service
FROM node:22

RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /app


COPY package*.json ./

RUN npm ci --omit=dev

COPY --from=0 /app/dist ./dist

RUN mkdir -p /app/storage/

RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser
RUN chown -R appuser:appgroup /app/storage && \
    chmod 760 /app/storage
USER appuser

EXPOSE 3000

CMD ["npm", "run", "serve"]

