# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  CONTAINER_TAG: video-processing-service

tasks:
  format:
    desc: Format using eslint
    cmds:
      - npm run lint:fix
    silent: true

  build:
    desc: Build a local container image.
    cmds:
      - podman build -t {{.CONTAINER_TAG}} .
    silent: true
    
  run:
    desc: Run the local container image. 
    cmds:
      - podman run -p 3000:3000 -d {{.CONTAINER_TAG}}:latest
    silent: true